# Infrared Perspective: Measure Attendance for Non-Ticketed, Outdoor Events

#### image processing, events, event planning

## A beginning.

Off the Grid is a food truck events company in the Bay Area that hosts 70 weekly events in 26 cities. As the company opens in new locations, a recurring issue at their grand opening events is tremendous event attendance met with insufficient food supply. With every food truck that sells out, there’s a loss of revenue and a dire impact on customer retention as wait time increases and customer satisfaction diminishes. Thus, the company needs a better way to forecast attendance in order to better prepare their food truck vendors for the potential turnout. A step towards this goal is figuring out a way to accurately estimate attendance for their events, which are non-ticketed, outdoors and temporary.

## A middle.

While the company currently utilizes clickers to count attendance, this method is prone to human error. There are also unaccounted discrepancies when there are multiple entrances and exits to the event. As a mobile event that resides in a location for 3-4 hours, they need a solution that is quick to setup and uninstall. 

Introducing Infrared Perspective. It’s a portable and compact, suitable for a fixed mount on Off the Grid’s trucks that are present at each of their events or for aerial use on drones when more visibility is necessary. The camera captures infrared images to maintain anonymity for customers. Infrared Perspective capture a series of images within an automatic timed sequence and the analysis software uses image processing to count the number of people per event. Infrared Perspective is affordable as its primary purpose is to detect human presence, minimizing its need for a wide detection range and high resolution that often brings up prices for infrared cameras.

## An end.

With the ability to successfully measure attendance, Off the Grid can start recording this data and eventually pair it with sales and promotional channel metrics such as Facebook event RSVPs or physical signage placement. Understanding the relationship between these components of the event will shed light on customer behavior (i.e. average spending, cuisine preferences), advertising ROI and allow for forecasting attendance at future events.
